import { Raleway } from "next/font/google";
import "./main.scss";
import "bootstrap-icons/font/bootstrap-icons.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Alex Lawnscaping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
